import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const appRoot = path.resolve(here, "..");
const packageJson = JSON.parse(await fs.readFile(path.join(appRoot, "package.json"), "utf8"));
const main = await fs.readFile(path.join(appRoot, "main.mjs"), "utf8");
const repoRoot = path.resolve(appRoot, "..");

assert.equal(packageJson.name, "codex-theme-creator-app");
assert.equal(packageJson.main, "main.mjs");
assert.ok(packageJson.scripts.start.includes("electron"), "desktop app can be launched with npm start");
assert.ok(packageJson.scripts.dist, "desktop app declares a distributable build command");
assert.ok(packageJson.devDependencies.electron, "desktop app declares Electron");
assert.ok(packageJson.devDependencies["electron-builder"], "desktop app declares a real desktop packager");
assert.ok(packageJson.dependencies?.["electron-updater"], "desktop app ships its update client at runtime");
assert.equal(packageJson.build.productName, "Codex Theme Creator", "packaged app has a product identity instead of generic Electron");
assert.equal(packageJson.build.appId, "com.swordingk.codexthemecreator", "packaged app has a stable app identifier");
assert.ok(packageJson.build.fileAssociations?.some((association) => association.ext === "ctheme"), "packaged app registers .ctheme files");
assert.equal(packageJson.build.icon, "build/icon-chatgpt-theme.icns", "macOS package uses the ChatGPT theme-manager icon");
assert.equal(packageJson.build.win.icon, "build/icon-chatgpt-theme.iconset/icon_256x256.png", "Windows package uses the same product icon");
assert.equal(packageJson.build.mac.hardenedRuntime, true, "public macOS builds enable the hardened runtime required for notarization");
assert.equal(packageJson.build.mac.entitlements, "build/entitlements.mac.plist", "public macOS builds declare explicit notarization entitlements");
assert.ok(packageJson.build.extraResources.length >= 4, "packaged app bundles its studio, engine, presets, and creator Skill");
assert.match(main, /startThemeStudioServer/, "desktop shell starts the embedded Theme Studio server");
assert.match(main, /ensureBundledCreatorSkill/, "first launch automatically provisions the bundled creator Skill");
assert.match(main, /creator-skill-version\.txt/, "creator Skill provisioning is versioned and does not rerun on every launch");
assert.match(main, /provisionCreatorSkill/, "desktop app uses a cross-platform creator Skill provisioner");
assert.match(main, /process\.resourcesPath/, "packaged app resolves bundled resources instead of the development checkout");
assert.match(main, /BrowserWindow/, "desktop shell creates a native window");
assert.match(main, /Tray/, "desktop shell creates a macOS menu bar / Windows tray icon");
assert.match(main, /Menu\.buildFromTemplate/, "tray icon has a native context menu");
assert.match(main, /setContextMenu/, "tray menu is attached to the tray icon");
assert.match(main, /popUpContextMenu/, "clicking the tray icon opens quick theme switching instead of the studio window");
assert.doesNotMatch(main, /nativeImage\.createEmpty\(\)/, "macOS tray must use a visible icon, not an empty placeholder");
assert.match(main, /setTemplateImage\(true\)/, "macOS tray icon should render as a native menu bar template image");
assert.doesNotMatch(main, /tray\.setTitle\(/, "macOS tray should use the product mark instead of a letter label");
assert.match(main, /tray-template\.png/, "macOS tray uses a dedicated 18px template asset instead of shrinking the app icon");
assert.match(main, /requestSingleInstanceLock/, "desktop app should avoid multiple stale controllers");
assert.match(main, /second-instance/, "launching again should focus the existing controller");
assert.match(main, /open-file/, "macOS double-clicked theme files are received by the desktop shell");
assert.match(main, /importThemeFile/, "desktop shell imports a .ctheme file through the existing validated importer");
assert.match(main, /\/api\/themes/, "tray menu can read the local theme library");
assert.match(main, /\/api\/quick-switch/, "tray menu can switch both saved and bundled themes");
assert.match(main, /恢复 Codex 默认外观/, "tray menu exposes the native Codex reset action");
assert.match(main, /event\.preventDefault\(\)/, "closing the window hides it to the tray instead of quitting");
assert.match(main, /checkForUpdates/, "desktop app checks GitHub Releases for newer versions");
assert.match(main, /update-downloaded/, "desktop app offers to restart after an update is downloaded");
assert.match(main, /检查更新/, "tray menu exposes a manual update check");
assert.ok(packageJson.build.publish?.some((item) => item.provider === "github"), "build publishes updater metadata to GitHub Releases");
await fs.access(path.join(repoRoot, "scripts", "start-theme-app.sh"));
await fs.access(path.join(repoRoot, "scripts", "start-theme-app.ps1"));
assert.ok(packageJson.scripts["dist:win"], "desktop app declares a Windows installer build");
assert.equal(packageJson.build.win.target[0].target, "nsis", "Windows distribution uses a real NSIS installer");
assert.match(packageJson.build.win.artifactName, /Setup/, "Windows installer has an understandable artifact name");
assert.equal(packageJson.build.nsis.oneClick, false, "Windows installer gives users a normal install wizard");
await fs.access(path.join(repoRoot, "engine", "windows", "scripts", "switch-theme-windows.ps1"));
await fs.access(path.join(repoRoot, "engine", "windows", "scripts", "restore-theme-windows.ps1"));

console.log("PASS: desktop app entry is packaged and starts Theme Studio.");
